"use client";

import Image from "next/image";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { getSellerStore, updateSellerStore } from "@/lib/seller-api";
import { uploadStoreBanner, uploadStoreLogo } from "@/lib/storage-api";
import { resolveImageUrl } from "@/utils/image-url";
import type { SellerStore, SellerStoreUpdateRequest } from "@/types/seller";

const empty: SellerStore = { id: 0, storeName: "", introduction: null, logoImageKey: null, bannerImageKey: null, customerServicePhone: null, customerServiceEmail: null, customerServiceHours: null, shippingGuide: null, returnExchangeGuide: null };
const display = (value: string | null) => value || "등록된 정보가 없습니다.";

export default function SellerStoreSettingsPage() {
  const [saved, setSaved] = useState(empty); const [draft, setDraft] = useState(empty); const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void getSellerStore().then((store) => { setSaved(store); setDraft(store); }).catch((e) => setError(e instanceof Error ? e.message : "스토어 정보를 불러오지 못했습니다.")).finally(() => setLoading(false)); }, []);
  const change = (field: keyof SellerStore) => (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setDraft((v) => ({ ...v, [field]: e.target.value }));
  const cancel = () => { setDraft(saved); setEditing(false); setError(""); };
  const upload = async (field: "logoImageKey" | "bannerImageKey", file?: File) => { if (!file) return; try { const key = field === "logoImageKey" ? await uploadStoreLogo(file) : await uploadStoreBanner(file); setDraft((v) => ({ ...v, [field]: key })); } catch (e) { setError(e instanceof Error ? e.message : "이미지 업로드에 실패했습니다."); } };
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(""); const request: SellerStoreUpdateRequest = { ...draft, storeName: draft.storeName.trim() }; if (request.storeName.length < 2 || request.storeName.length > 30) { setError("스토어명은 2~30자로 입력해 주세요."); return; } setSaving(true); try { const next = await updateSellerStore(request); setSaved(next); setDraft(next); setEditing(false); setMessage("스토어 설정을 저장했습니다."); } catch (e) { setError(e instanceof Error ? e.message : "저장에 실패했습니다."); } finally { setSaving(false); } };
  if (loading) return <main className="seller-settings-page"><div className="seller-settings-container"><p>스토어 정보를 불러오는 중입니다.</p></div></main>;
  const current = editing ? draft : saved;
  return <main className="seller-settings-page"><div className="seller-settings-container"><header className="seller-settings-header"><div><p className="seller-settings-eyebrow">스토어 관리</p><h1>스토어 설정</h1><p>구매자에게 노출되는 스토어 정보와 고객 안내 정보를 관리합니다.</p></div><div className="seller-settings-actions">{editing ? <><button type="button" className="seller-settings-secondary" onClick={cancel} disabled={saving}>취소</button><button type="submit" form="seller-settings-form" className="seller-settings-primary" disabled={saving}>{saving ? "저장 중..." : "저장"}</button></> : <button type="button" className="seller-settings-primary" onClick={() => { setDraft(saved); setEditing(true); }}>수정</button>}</div></header>{message && <p className="seller-settings-success" role="status">{message}</p>}{error && <p className="seller-settings-error" role="alert">{error}</p>}
    <section className="seller-settings-card"><div className="seller-settings-card-heading"><h2>스토어 정보</h2><span>기본 공개 정보</span></div><div className="seller-settings-store-info"><div className="seller-settings-logo">{current.logoImageKey ? <Image src={resolveImageUrl(current.logoImageKey) ?? ""} alt="스토어 로고" width={96} height={96} /> : <span>{current.storeName.charAt(0) || "G"}</span>}</div>{editing ? <div className="seller-settings-fields"><label>스토어명<input value={draft.storeName} maxLength={30} onChange={change("storeName")} /><small>{draft.storeName.length}/30</small></label><label>스토어 소개<textarea value={draft.introduction ?? ""} maxLength={500} onChange={change("introduction")} /><small>{(draft.introduction ?? "").length}/500</small></label></div> : <div className="seller-settings-values"><div><b>스토어명</b><p>{display(current.storeName)}</p></div><div><b>스토어 소개</b><p className="seller-settings-preline">{display(current.introduction)}</p></div></div>}</div>{editing && <div className="seller-settings-upload"><label>로고<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => void upload("logoImageKey", e.target.files?.[0])} /></label><small>JPG, PNG, WebP · 최대 5MB · 1:1 권장</small>{draft.logoImageKey && <button type="button" className="seller-settings-link" onClick={() => setDraft((v) => ({ ...v, logoImageKey: null }))}>로고 삭제</button>}</div>}</section>
    <section className="seller-settings-card"><div className="seller-settings-card-heading"><h2>스토어 배너</h2><span>구매자 미리보기</span></div><div className="seller-settings-banner">{current.bannerImageKey ? <Image src={resolveImageUrl(current.bannerImageKey) ?? ""} alt="스토어 배너" width={880} height={220} /> : <span>등록된 배너가 없습니다.</span>}</div>{editing && <div className="seller-settings-upload"><label>배너<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => void upload("bannerImageKey", e.target.files?.[0])} /></label><small>JPG, PNG, WebP · 최대 10MB · 가로형 권장</small>{draft.bannerImageKey && <button type="button" className="seller-settings-link" onClick={() => setDraft((v) => ({ ...v, bannerImageKey: null }))}>배너 삭제</button>}</div>}</section>
    <form id="seller-settings-form" onSubmit={submit}><section className="seller-settings-card"><div className="seller-settings-card-heading"><h2>고객센터 정보</h2></div>{editing ? <div className="seller-settings-grid"><label>전화번호<input value={draft.customerServicePhone ?? ""} maxLength={30} onChange={change("customerServicePhone")} /></label><label>이메일<input type="email" value={draft.customerServiceEmail ?? ""} maxLength={255} onChange={change("customerServiceEmail")} /></label><label>운영시간<input value={draft.customerServiceHours ?? ""} maxLength={255} onChange={change("customerServiceHours")} /></label></div> : <div className="seller-settings-grid">{[["전화번호", current.customerServicePhone], ["이메일", current.customerServiceEmail], ["운영시간", current.customerServiceHours]].map(([label, item]) => <div key={label as string}><b>{label}</b><p>{display(item as string | null)}</p></div>)}</div>}</section><section className="seller-settings-card"><div className="seller-settings-card-heading"><h2>배송 안내</h2></div>{editing ? <label className="seller-settings-full-field"><textarea value={draft.shippingGuide ?? ""} maxLength={1000} onChange={change("shippingGuide")} /><small>{(draft.shippingGuide ?? "").length}/1000</small></label> : <p className="seller-settings-read-text">{display(current.shippingGuide)}</p>}</section><section className="seller-settings-card"><div className="seller-settings-card-heading"><h2>반품/교환 안내</h2></div>{editing ? <label className="seller-settings-full-field"><textarea value={draft.returnExchangeGuide ?? ""} maxLength={1000} onChange={change("returnExchangeGuide")} /><small>{(draft.returnExchangeGuide ?? "").length}/1000</small></label> : <p className="seller-settings-read-text">{display(current.returnExchangeGuide)}</p>}</section></form>
  </div></main>;
}
