"use client";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, Suspense, useCallback, useEffect, useState } from "react";
import Pagination from "@/components/common/Pagination";
import { getAdminOrders } from "@/lib/admin-api";
import type { AdminOrderPage, AdminOrderStatus, AdminPaymentStatus } from "@/types/admin";

const orderStatuses: AdminOrderStatus[] = ["ORDERED","PENDING_PAYMENT","PAID","PAYMENT_FAILED","PAYMENT_EXPIRED","CANCELLED"];
const paymentStatuses: AdminPaymentStatus[] = ["READY","CONFIRMING","PAID","PARTIALLY_CANCELED","FAILED","EXPIRED","CANCELING","CANCELED"];
const labels: Record<string,string> = { ORDERED:"주문 생성",PENDING_PAYMENT:"결제 대기",PAID:"결제 완료",PAYMENT_FAILED:"결제 실패",PAYMENT_EXPIRED:"결제 만료",CANCELLED:"취소",READY:"결제 준비",CONFIRMING:"승인 중",PARTIALLY_CANCELED:"부분 취소",FAILED:"실패",EXPIRED:"만료",CANCELING:"취소 중",CANCELED:"취소 완료",PREPARING:"상품 준비",SHIPPED:"배송 중",DELIVERED:"배송 완료" };
const dt=(v:string|null)=>v?new Date(v).toLocaleString("ko-KR"):"-";
function Content(){const router=useRouter(),sp=useSearchParams(); const page=Math.max(0,Number(sp.get("page"))||0), keyword=sp.get("keyword")?.trim()??"";
 const ov=sp.get("orderStatus"),pv=sp.get("paymentStatus"); const orderStatus=orderStatuses.includes(ov as AdminOrderStatus)?ov as AdminOrderStatus:undefined; const paymentStatus=paymentStatuses.includes(pv as AdminPaymentStatus)?pv as AdminPaymentStatus:undefined;
 const [data,setData]=useState<AdminOrderPage|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""); const [q,setQ]=useState(keyword);
 const href=useCallback((c:Record<string,string|number|undefined>)=>{const n=new URLSearchParams(sp.toString());Object.entries(c).forEach(([k,v])=>v===undefined||v===""||(k==="page"&&v===0)?n.delete(k):n.set(k,String(v)));return n.toString()?`/admin/orders?${n}`:"/admin/orders"},[sp]);
 const load=useCallback(async()=>{try{setLoading(true);setError("");const r=await getAdminOrders({page,size:20,keyword:keyword||undefined,orderStatus,paymentStatus});if(page>0&&(r.totalPages===0||page>=r.totalPages)){router.replace(href({page:Math.max(0,r.totalPages-1)}),{scroll:false});return}setData(r)}catch(e){setError(e instanceof Error?e.message:"주문 목록을 불러오지 못했습니다.")}finally{setLoading(false)}},[href,keyword,orderStatus,page,paymentStatus,router]);
 useEffect(()=>{// URL 조건에 맞춰 주문 목록을 동기화한다.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 void load()},[load]);
 const summary=(name:string|null,count:number)=>name?`${name}${count>1?` 외 ${count-1}종`:""}`:"-";
 return <main className="admin-users-page admin-orders-page"><header className="admin-users-header"><div><p>ORDER MANAGEMENT</p><h1>주문 관리</h1><span>전체 주문과 결제·판매자별 처리 상태를 조회합니다.</span></div><div><small>검색 결과</small><strong>{loading||error||!data?"-":data.totalElements.toLocaleString("ko-KR")}</strong><span>건</span></div></header>
 <section className="admin-user-filter-panel"><form className="admin-user-search" onSubmit={(e:FormEvent)=>{e.preventDefault();router.push(href({keyword:q.trim()||undefined,page:0}),{scroll:false})}}><label className="admin-user-search-input"><span className="sr-only">주문 검색</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="주문번호, 구매자 이름 또는 이메일"/></label><button>검색</button></form><div className="admin-user-filters"><label><span>주문 상태</span><select value={orderStatus??""} onChange={e=>router.push(href({orderStatus:e.target.value||undefined,page:0}),{scroll:false})}><option value="">전체</option>{orderStatuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label><span>결제 상태</span><select value={paymentStatus??""} onChange={e=>router.push(href({paymentStatus:e.target.value||undefined,page:0}),{scroll:false})}><option value="">전체</option>{paymentStatuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label></div></section>
 {error&&<div className="admin-dashboard-error" role="alert"><span>{error}</span><button onClick={load}>다시 시도</button></div>}<section className="admin-user-list-section"><div className="admin-user-list-heading"><h2>주문 목록</h2>{data&&!error&&<span>총 {data.totalElements.toLocaleString("ko-KR")}건</span>}</div>{loading&&!data?<div className="admin-user-state">주문 목록을 불러오고 있습니다.</div>:data?.content.length?<div className="admin-user-table-wrap"><table className="admin-user-table admin-order-table"><thead><tr><th>주문번호</th><th>구매자</th><th>상품</th><th>결제금액</th><th>주문 상태</th><th>결제 상태</th><th>판매자 주문</th><th>주문일</th><th></th></tr></thead><tbody>{data.content.map(o=><tr key={o.orderId}><td data-label="주문번호"><Link href={`/admin/orders/${o.orderId}`} className="admin-order-number">{o.orderNumber}</Link></td><td data-label="구매자"><Link href={`/admin/users/${o.userId}`}>{o.userName}</Link><small>{o.userEmail}</small></td><td data-label="상품">{summary(o.representativeProductName,o.productTypeCount)}</td><td data-label="결제금액">{o.totalAmount.toLocaleString("ko-KR")}원</td><td data-label="주문 상태"><span className="admin-order-badge">{labels[o.orderStatus]}</span></td><td data-label="결제 상태">{o.paymentStatus?labels[o.paymentStatus]:"-"}</td><td data-label="판매자 주문">{o.sellerOrderStatuses.map(s=>labels[s]).join(" · ")||"-"}</td><td data-label="주문일">{dt(o.orderedAt)}</td><td><Link href={`/admin/orders/${o.orderId}`} className="admin-user-detail-link">상세</Link></td></tr>)}</tbody></table></div>:<div className="admin-user-state"><strong>조건에 맞는 주문이 없습니다.</strong><span>검색어나 필터 조건을 변경해 보세요.</span></div>}<Pagination currentPage={data?.page??page} totalPages={data?.totalPages??0} ariaLabel="주문 목록 페이지" mode="numbers" disabled={loading} getPageHref={p=>href({page:p})} scroll={false} className="admin-user-pagination"/></section></main>}
export default function Page(){return <Suspense fallback={<div className="admin-user-state">주문 목록을 준비하고 있습니다.</div>}><Content/></Suspense>}
