"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { getAdminOrder } from "@/lib/admin-api";
import type { AdminOrderDetail } from "@/types/admin";
const labels:Record<string,string>={ORDERED:"주문 생성",PENDING_PAYMENT:"결제 대기",PAID:"결제 완료",PAYMENT_FAILED:"결제 실패",PAYMENT_EXPIRED:"결제 만료",CANCELLED:"취소",READY:"준비",CONFIRMING:"승인 중",PARTIALLY_CANCELED:"부분 취소",FAILED:"실패",EXPIRED:"만료",CANCELING:"취소 중",CANCELED:"취소 완료",PREPARING:"상품 준비",SHIPPED:"배송 중",DELIVERED:"배송 완료",ORIGINAL_OUTBOUND:"최초 출고",RETURN_COLLECTION:"반품 회수",EXCHANGE_COLLECTION:"교환 회수",EXCHANGE_OUTBOUND:"교환 재출고"};
const dt=(v:string|null)=>v?new Date(v).toLocaleString("ko-KR"):"-"; const won=(v:number)=>`${v.toLocaleString("ko-KR")}원`;
export default function Page(){const id=Number(useParams<{orderId:string}>().orderId);const [o,setO]=useState<AdminOrderDetail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=useCallback(async()=>{if(!Number.isSafeInteger(id)||id<1){setError("올바르지 않은 주문 번호입니다.");setLoading(false);return}try{setLoading(true);setError("");setO(await getAdminOrder(id))}catch(e){setError(e instanceof Error?e.message:"주문 정보를 불러오지 못했습니다.")}finally{setLoading(false)}},[id]);useEffect(()=>{// URL의 주문 번호에 맞춰 상세 정보를 동기화한다.
// eslint-disable-next-line react-hooks/set-state-in-effect
void load()},[load]);return <main className="admin-user-detail-page admin-order-detail-page"><Link href="/admin/orders" className="admin-user-back-link">← 주문 목록으로 돌아가기</Link>{error&&<div className="admin-dashboard-error"><span>{error}</span><button onClick={load}>다시 시도</button></div>}{loading&&!o?<div className="admin-user-state">주문 정보를 불러오고 있습니다.</div>:o?<><header className="admin-user-detail-header"><div><p>ORDER DETAIL · #{o.orderId}</p><h1>{o.orderNumber}</h1><span>{dt(o.orderedAt)}</span></div><span className="admin-order-badge">{labels[o.orderStatus]}</span></header><div className="admin-user-detail-grid">
<section className="admin-user-detail-card"><header><p>ORDER</p><h2>주문 기본 정보</h2></header><dl><div><dt>상품 금액</dt><dd>{won(o.totalProductAmount)}</dd></div><div><dt>배송비</dt><dd>{won(o.totalShippingFee)}</dd></div><div><dt>총 결제금액</dt><dd>{won(o.totalAmount)}</dd></div><div><dt>주문 상태</dt><dd>{labels[o.orderStatus]}</dd></div></dl></section>
<section className="admin-user-detail-card"><header><p>BUYER</p><h2>구매자</h2></header><dl><div><dt>이름</dt><dd>{o.buyer.name}</dd></div><div><dt>이메일</dt><dd>{o.buyer.email||"-"}</dd></div><div><dt>권한 / 상태</dt><dd>{o.buyer.role} · {o.buyer.status}</dd></div></dl><Link href={`/admin/users/${o.buyer.userId}`} className="admin-seller-owner-button">회원 상세 보기 →</Link></section>
<section className="admin-user-detail-card"><header><p>RECIPIENT</p><h2>수령 정보</h2></header><dl><div><dt>수령인</dt><dd>{o.recipient.name}</dd></div><div><dt>연락처</dt><dd>{o.recipient.phone}</dd></div><div><dt>우편번호</dt><dd>{o.recipient.postalCode}</dd></div><div><dt>주소</dt><dd>{o.recipient.address} {o.recipient.detailAddress}</dd></div></dl></section>
<section className="admin-user-detail-card"><header><p>PAYMENT</p><h2>결제 정보</h2></header>{o.payment?<dl><div><dt>결제 상태</dt><dd>{labels[o.payment.status]}</dd></div><div><dt>금액</dt><dd>{won(o.payment.amount)}</dd></div><div><dt>결제 수단</dt><dd>{o.payment.method||"-"} {o.payment.easyPayProvider||""}</dd></div><div><dt>요청 / 승인</dt><dd>{dt(o.payment.requestedAt)} / {dt(o.payment.approvedAt)}</dd></div><div><dt>PG 상태</dt><dd>{o.payment.providerStatus||"-"}</dd></div></dl>:<p className="admin-user-detail-empty">결제 정보가 없습니다.</p>}</section>
<section className="admin-user-detail-card"><header><p>CLAIMS & REFUNDS</p><h2>클레임 / 환불 요약</h2></header><dl className="admin-user-activity"><div><dt>취소</dt><dd>{o.claims.cancellationCount}</dd></div><div><dt>반품</dt><dd>{o.claims.returnCount}</dd></div><div><dt>교환</dt><dd>{o.claims.exchangeCount}</dd></div></dl><p className="admin-order-refund">성공 환불 {o.refund.succeededCount}건 · {won(o.refund.succeededAmount)}</p></section>
<section className="admin-user-detail-card admin-order-groups"><header><p>SELLER ORDERS</p><h2>판매자별 주문</h2></header>{o.sellerOrders.map(g=><article key={g.sellerOrderId} className="admin-order-group"><header><div><Link href={`/admin/sellers/${g.sellerId}`}>{g.storeName}</Link><small>SellerOrder #{g.sellerOrderId}</small></div><span className="admin-order-badge">{labels[g.status]}</span></header><div className="admin-order-item-list">{g.items.map(i=><div key={i.orderItemId}><div><Link href={`/admin/products/${i.productId}`}>{i.productName}</Link><small>{i.optionSnapshot||"옵션 없음"}</small></div><span>{won(i.unitPrice)} × {i.quantity}</span><strong>{won(i.totalPrice)}</strong><small>취소 {i.canceledQuantity} · 반품 {i.returnedQuantity} · 교환 {i.exchangedQuantity} · 구매확정 {i.confirmedQuantity}</small></div>)}</div><div className="admin-order-shipments"><h3>배송 이력</h3>{g.shipments.length?g.shipments.map(s=><div key={s.shipmentId}><span>{labels[s.type]} · {labels[s.status]}</span><strong>{s.shippingCompany} {s.trackingNumber}</strong><small>출고 {dt(s.shippedAt)} · 완료 {dt(s.deliveredAt)}</small></div>):<p>등록된 배송 이력이 없습니다.</p>}</div></article>)}</section>
</div></>:null}</main>}
