"use client";

import Image from "next/image";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import ReturnImageViewerModal from "@/components/return/ReturnImageViewerModal";
import { approveSellerExchangeRequest, collectSellerExchange, deliverSellerExchange, getSellerExchangeRequest, inspectSellerExchange, receiveSellerExchange, rejectSellerExchangeRequest, reshipSellerExchange } from "@/lib/seller-exchange-api";
import { useAuthStore } from "@/stores/auth-store";
import { EXCHANGE_INSPECTION_LABELS, EXCHANGE_REASON_LABELS, EXCHANGE_RESPONSIBILITY_LABELS, EXCHANGE_SHIPMENT_STATUS_LABELS, EXCHANGE_STATUS_LABELS, type ExchangeInspectionResult, type ExchangeRequest, type ExchangeResponsibility } from "@/types/exchange";

type Mode = "approve" | "reject" | "collect" | "receive" | "inspect" | "reship" | "deliver" | null;
const date = (value: string | null | undefined) => value ? new Intl.DateTimeFormat("ko-KR", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "-";
const money = (value: number | null | undefined) => typeof value === "number" && Number.isFinite(value) ? `${value.toLocaleString("ko-KR")}원` : "-";

export default function SellerExchangeDetailPage() {
  const params = useParams<{ exchangeRequestId: string }>(); const id = Number(params.exchangeRequestId); const router = useRouter();
  const initialized = useAuthStore((s) => s.initialized); const user = useAuthStore((s) => s.user); const authenticated = useAuthStore((s) => s.isAuthenticated);
  const [request, setRequest] = useState<ExchangeRequest | null>(null); const [loading, setLoading] = useState(true); const [processing, setProcessing] = useState(false); const [error, setError] = useState(""); const [actionError, setActionError] = useState(""); const [mode, setMode] = useState<Mode>(null);
  const [responsibility, setResponsibility] = useState<ExchangeResponsibility | "">(""); const [rejectReason, setRejectReason] = useState(""); const [shippingCompany, setShippingCompany] = useState(""); const [trackingNumber, setTrackingNumber] = useState(""); const [inspections, setInspections] = useState<Record<number, ExchangeInspectionResult>>({}); const [viewer, setViewer] = useState<number | null>(null);
  const load = useCallback(async (quiet = false) => { await Promise.resolve(); if (!Number.isInteger(id) || id <= 0) { setError("올바른 교환 요청 번호가 아닙니다."); setLoading(false); return; } try { if (!quiet) setLoading(true); setError(""); setRequest(await getSellerExchangeRequest(id)); } catch (e) { setError(e instanceof Error ? e.message : "교환 요청을 불러오지 못했습니다."); } finally { if (!quiet) setLoading(false); } }, [id]);
  useEffect(() => { if (!initialized) return; if (!authenticated || !user) { router.replace("/login"); return; } if (user.role !== "SELLER" && user.role !== "ADMIN") { router.replace("/seller"); return; } const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [authenticated, initialized, load, router, user]);
  const resetForm = () => { setMode(null); setActionError(""); setResponsibility(""); setRejectReason(""); setShippingCompany(""); setTrackingNumber(""); setInspections({}); };
  const perform = async (action: () => Promise<ExchangeRequest>) => { if (processing) return; try { setProcessing(true); setActionError(""); await action(); setRequest(await getSellerExchangeRequest(id)); resetForm(); } catch (e) { const message = e instanceof Error ? e.message : ""; setActionError(message || "교환 상태가 변경되었거나 요청을 처리하지 못했습니다."); try { setRequest(await getSellerExchangeRequest(id)); } catch {} } finally { setProcessing(false); } };
  const approve = () => { if (!request || request.status !== "REQUESTED") return; if (request.reasonType === "OTHER" && !responsibility) { setActionError("기타 사유는 귀책 주체를 선택해주세요."); return; } void perform(() => approveSellerExchangeRequest(id, request.reasonType === "OTHER" ? responsibility || null : null)); };
  const reject = () => { const reason = rejectReason.trim(); if (!reason) { setActionError("교환 거절 사유를 입력해주세요."); return; } void perform(() => rejectSellerExchangeRequest(id, reason)); };
  const ship = (kind: "collect" | "reship") => { const company = shippingCompany.trim(); const tracking = trackingNumber.trim(); if (!company || !tracking) { setActionError("택배사와 송장번호를 모두 입력해주세요."); return; } void perform(() => kind === "collect" ? collectSellerExchange(id, company, tracking) : reshipSellerExchange(id, company, tracking)); };
  const inspect = () => { if (!request || request.items.some((item) => !inspections[item.orderItemId])) { setActionError("모든 상품의 재입고 검수 결과를 선택해주세요."); return; } void perform(() => inspectSellerExchange(id, { items: request.items.map((item) => ({ orderItemId: item.orderItemId, inspectionResult: inspections[item.orderItemId] })) })); };
  if (!initialized || !authenticated || !user || loading) return <div className="seller-orders-auth-loading">교환 요청을 확인하고 있습니다.</div>;
  if (error || !request) return <main className="seller-orders-page"><div className="common-inner seller-orders-container"><div className="seller-orders-state seller-orders-state-error"><p>{error || "교환 요청을 확인할 수 없습니다."}</p><button type="button" onClick={() => void load()}>다시 시도</button><Link href="/seller/orders/exchanges">목록으로</Link></div></div></main>;
  const timeline = [["요청", request.requestedAt], ["승인", request.approvedAt], ["결제 대기", request.paymentPendingAt], ["회수 가능", request.collectingAt], ["입고", request.receivedAt], ["검수", request.inspectedAt], ["재배송", request.reshippingAt], ["완료", request.completedAt]].filter((entry): entry is [string, string] => Boolean(entry[1]));
  return <main className="seller-orders-page seller-exchanges-page"><div className="common-inner seller-orders-container seller-order-detail-container">
    <header className="seller-order-detail-header"><div><p>EXCHANGE DETAIL</p><h1>교환 요청 상세</h1><span>주문 ID #{request.orderId} · 요청 #{request.exchangeRequestId}</span></div><Link href="/seller/orders/exchanges">목록으로</Link></header>
    <section className="seller-order-detail-summary seller-return-summary"><div><span>요청 상태</span><strong className={`seller-return-status seller-exchange-status-${request.status.toLowerCase()}`}>{EXCHANGE_STATUS_LABELS[request.status]}</strong></div><div><span>요청일시</span><strong>{date(request.requestedAt)}</strong></div><div><span>귀책</span><strong>{request.responsibility ? EXCHANGE_RESPONSIBILITY_LABELS[request.responsibility] : "확정 전"}</strong></div></section>
    {request.status === "PAYMENT_PENDING" && <p className="seller-return-state-message processing">구매자의 교환배송비 결제를 기다리고 있습니다. 결제기한: {date(request.paymentDueAt)}</p>}
    {request.status === "COMPLETED" && <p className="seller-return-state-message success">교환품 배송과 교환 처리가 완료되었습니다.</p>}
    {request.status === "REJECTED" && <p className="seller-return-state-message rejected">거절된 교환 요청입니다.{request.rejectedReason ? ` 사유: ${request.rejectedReason}` : ""}</p>}
    {request.status === "CANCELED" && <p className="seller-return-state-message rejected">교환 요청이 취소되었습니다.</p>}
    {request.status === "FAILED" && <p className="seller-return-state-message failed">교환 처리 중 문제가 발생했습니다.</p>}

    <section className="seller-order-detail-section"><h2>요청 정보</h2><dl className="seller-order-detail-info-list seller-return-info-list"><div><dt>주문</dt><dd><Link href={`/seller/orders/${request.sellerOrderId}`}>주문 ID #{request.orderId} 상세보기</Link></dd></div><div><dt>교환 사유</dt><dd>{EXCHANGE_REASON_LABELS[request.reasonType]} · {request.reason}</dd></div><div><dt>귀책</dt><dd>{request.responsibility ? EXCHANGE_RESPONSIBILITY_LABELS[request.responsibility] : "판매자 확정 전"}</dd></div>{request.rejectedReason && <div><dt>거절 사유</dt><dd>{request.rejectedReason}</dd></div>}</dl>{timeline.length > 0 && <div className="seller-return-timeline">{timeline.map(([label, value]) => <div key={label}><span>{label}</span><strong>{date(value)}</strong></div>)}</div>}</section>
    {request.images.length > 0 && <section className="seller-order-detail-section"><h2>첨부 이미지</h2><div className="seller-return-images">{request.images.map((image, index) => <button key={image.imageId} type="button" className="return-image-thumbnail-button" aria-label={`교환 증빙 이미지 ${index + 1} 크게 보기`} onClick={() => setViewer(index)}><Image src={image.url} alt={`교환 증빙 이미지 ${index + 1}`} width={140} height={140} unoptimized /></button>)}</div></section>}
    <section className="seller-order-detail-section"><h2>교환 상품</h2><div className="seller-exchange-items">{request.items.map((item) => <article key={item.orderItemId} className="seller-exchange-item"><div><span>원 상품</span><strong>{item.originalProductName}</strong><small>{item.originalOptionSnapshot ?? "기본 상품"}</small></div><span className="seller-exchange-arrow" aria-hidden="true">→</span><div><span>교환 대상</span><strong>{item.targetProductName}</strong><small>{item.targetOptionSnapshot ?? "기본 상품"}</small></div><dl><div><dt>수량</dt><dd>{item.quantity}개</dd></div><div><dt>단가</dt><dd>{money(item.targetUnitPrice)}</dd></div><div><dt>검수</dt><dd>{item.inspectionResult ? EXCHANGE_INSPECTION_LABELS[item.inspectionResult] : "검수 전"}</dd></div></dl></article>)}</div></section>
    <div className="seller-return-detail-columns"><Address title="회수지" recipient={request.collectionRecipientName} phone={request.collectionPhone} postalCode={request.collectionPostalCode} address={request.collectionAddress} detail={request.collectionAddressDetail} /><Address title="재배송지" recipient={request.reshippingRecipientName} phone={request.reshippingPhone} postalCode={request.reshippingPostalCode} address={request.reshippingAddress} detail={request.reshippingAddressDetail} /></div>
    <div className="seller-return-detail-columns"><Shipment title="교환 상품 회수" shipment={request.collectionShipment} empty="아직 회수 배송이 등록되지 않았습니다." /><Shipment title="교환 상품 재배송" shipment={request.outboundShipment} empty="아직 교환품 재배송이 등록되지 않았습니다." /></div>

    <section className="seller-order-detail-section seller-order-action-section seller-return-action-section"><h2>교환 처리</h2>
      {request.status === "REQUESTED" && mode === null && <div className="seller-return-action-buttons"><button type="button" disabled={processing} onClick={() => setMode("approve")}>교환 승인</button><button type="button" className="danger-secondary" disabled={processing} onClick={() => setMode("reject")}>교환 거절</button></div>}
      {request.status === "REQUESTED" && mode === "approve" && <div className="seller-return-action-form"><strong>교환 요청을 승인합니다.</strong>{request.reasonType === "OTHER" ? <label><span>귀책 주체</span><select value={responsibility} disabled={processing} onChange={(e) => setResponsibility(e.target.value as ExchangeResponsibility)}><option value="">선택해주세요</option><option value="BUYER">구매자 귀책</option><option value="SELLER">판매자 귀책</option></select></label> : <p>사유에 따라 {EXCHANGE_RESPONSIBILITY_LABELS[request.responsibility ?? (request.reasonType === "CHANGE_OF_MIND" || request.reasonType === "OPTION_MISTAKE" ? "BUYER" : "SELLER")]}으로 처리됩니다.</p>}<FormButtons processing={processing} close={resetForm} submit={approve} label="승인 확정" busyLabel="승인 처리 중..." disabled={request.reasonType === "OTHER" && !responsibility} /></div>}
      {request.status === "REQUESTED" && mode === "reject" && <div className="seller-return-action-form"><label><span>거절 사유 <small>{rejectReason.length}/500</small></span><textarea rows={4} maxLength={500} value={rejectReason} disabled={processing} onChange={(e) => setRejectReason(e.target.value)} /></label><FormButtons processing={processing} close={resetForm} submit={reject} label="거절 확정" busyLabel="거절 처리 중..." disabled={!rejectReason.trim()} danger /></div>}
      {request.status === "COLLECTING" && !request.collectionShipment && mode === null && <ActionButton label="회수 시작" processing={processing} onClick={() => setMode("collect")} />}
      {request.status === "COLLECTING" && !request.collectionShipment && mode === "collect" && <ShippingForm title="회수 배송 등록" processing={processing} company={shippingCompany} tracking={trackingNumber} setCompany={setShippingCompany} setTracking={setTrackingNumber} close={resetForm} submit={() => ship("collect")} busyLabel="회수 등록 중..." />}
      {request.status === "COLLECTING" && request.collectionShipment?.status === "SHIPPED" && mode === null && <ActionButton label="입고 처리" processing={processing} onClick={() => setMode("receive")} />}
      {request.status === "COLLECTING" && mode === "receive" && <ConfirmForm title="회수 상품을 입고 처리할까요?" description="입고 후 모든 상품의 재입고 가능 여부를 검수할 수 있습니다." processing={processing} close={resetForm} submit={() => void perform(() => receiveSellerExchange(id))} label="입고 확정" busyLabel="입고 처리 중..." />}
      {request.status === "RECEIVED" && mode === null && <ActionButton label="전체 상품 검수" processing={processing} onClick={() => setMode("inspect")} />}
      {request.status === "RECEIVED" && mode === "inspect" && <div className="seller-return-inspection"><p>검수 결과는 원 상품의 재입고 가능 여부입니다. 재입고 불가여도 교환은 계속됩니다.</p>{request.items.map((item) => <fieldset key={item.orderItemId}><legend>{item.originalProductName}<small>{item.originalOptionSnapshot ?? "기본 상품"}</small></legend>{(["RESTOCKABLE", "NON_RESTOCKABLE"] as const).map((value) => <label key={value}><input type="radio" name={`inspection-${item.orderItemId}`} checked={inspections[item.orderItemId] === value} disabled={processing} onChange={() => setInspections((current) => ({ ...current, [item.orderItemId]: value }))} />{EXCHANGE_INSPECTION_LABELS[value]}</label>)}</fieldset>)}<FormButtons processing={processing} close={resetForm} submit={inspect} label="검수 완료" busyLabel="검수 처리 중..." disabled={request.items.some((item) => !inspections[item.orderItemId])} /></div>}
      {request.status === "INSPECTED" && mode === null && <ActionButton label="교환품 발송" processing={processing} onClick={() => setMode("reship")} />}
      {request.status === "INSPECTED" && mode === "reship" && <ShippingForm title="교환품 재배송 등록" processing={processing} company={shippingCompany} tracking={trackingNumber} setCompany={setShippingCompany} setTracking={setTrackingNumber} close={resetForm} submit={() => ship("reship")} busyLabel="재배송 등록 중..." />}
      {request.status === "RESHIPPING" && request.outboundShipment?.status === "SHIPPED" && mode === null && <ActionButton label="배송 완료" processing={processing} onClick={() => setMode("deliver")} />}
      {request.status === "RESHIPPING" && mode === "deliver" && <ConfirmForm title="교환품 배송을 완료 처리할까요?" description="완료하면 교환 수량이 최종 반영되고 다시 처리할 수 없습니다." processing={processing} close={resetForm} submit={() => void perform(() => deliverSellerExchange(id))} label="배송 완료 확정" busyLabel="배송 완료 처리 중..." />}
      {!["REQUESTED", "COLLECTING", "RECEIVED", "INSPECTED", "RESHIPPING"].includes(request.status) && <p className="seller-order-action-notice">{request.status === "PAYMENT_PENDING" ? "구매자의 교환배송비 결제를 기다리고 있습니다." : request.status === "COMPLETED" ? "교환 처리가 완료되었습니다." : `${EXCHANGE_STATUS_LABELS[request.status]} 상태에는 판매자 추가 작업이 없습니다.`}</p>}
      {actionError && <p className="seller-order-action-error">{actionError}</p>}
    </section>
    {viewer !== null && <ReturnImageViewerModal images={request.images} initialIndex={viewer} label="교환 증빙 이미지" onClose={() => setViewer(null)} />}
  </div></main>;
}

function Address({ title, recipient, phone, postalCode, address, detail }: { title: string; recipient: string; phone: string; postalCode: string; address: string; detail: string | null }) { return <section className="seller-order-detail-section"><h2>{title}</h2><dl className="seller-order-detail-info-list seller-return-info-list"><div><dt>이름</dt><dd>{recipient}</dd></div><div><dt>전화</dt><dd>{phone}</dd></div><div><dt>주소</dt><dd>({postalCode}) {address} {detail ?? ""}</dd></div></dl></section>; }
function Shipment({ title, shipment, empty }: { title: string; shipment: ExchangeRequest["collectionShipment"]; empty: string }) { return <section className="seller-order-detail-section"><h2>{title}</h2>{shipment ? <dl className="seller-order-detail-info-list seller-return-info-list"><div><dt>택배사</dt><dd>{shipment.shippingCompany ?? "-"}</dd></div><div><dt>송장번호</dt><dd>{shipment.trackingNumber ?? "-"}</dd></div><div><dt>상태</dt><dd>{EXCHANGE_SHIPMENT_STATUS_LABELS[shipment.status]}</dd></div><div><dt>발송일</dt><dd>{date(shipment.shippedAt)}</dd></div><div><dt>완료일</dt><dd>{date(shipment.deliveredAt)}</dd></div></dl> : <p className="seller-order-action-notice">{empty}</p>}</section>; }
function ActionButton({ label, processing, onClick }: { label: string; processing: boolean; onClick: () => void }) { return <div className="seller-return-action-buttons"><button type="button" disabled={processing} onClick={onClick}>{label}</button></div>; }
function FormButtons({ processing, close, submit, label, busyLabel, disabled = false, danger = false }: { processing: boolean; close: () => void; submit: () => void; label: string; busyLabel: string; disabled?: boolean; danger?: boolean }) { return <div><button type="button" className="secondary" disabled={processing} onClick={close}>돌아가기</button><button type="button" className={danger ? "danger" : undefined} disabled={processing || disabled} onClick={submit}>{processing ? busyLabel : label}</button></div>; }
function ShippingForm({ title, processing, company, tracking, setCompany, setTracking, close, submit, busyLabel }: { title: string; processing: boolean; company: string; tracking: string; setCompany: (v: string) => void; setTracking: (v: string) => void; close: () => void; submit: () => void; busyLabel: string }) { return <div className="seller-return-action-form"><strong>{title}</strong><label><span>택배사</span><input maxLength={100} value={company} disabled={processing} onChange={(e) => setCompany(e.target.value)} /></label><label><span>송장번호</span><input maxLength={100} value={tracking} disabled={processing} onChange={(e) => setTracking(e.target.value)} /></label><FormButtons processing={processing} close={close} submit={submit} label="등록" busyLabel={busyLabel} disabled={!company.trim() || !tracking.trim()} /></div>; }
function ConfirmForm({ title, description, processing, close, submit, label, busyLabel }: { title: string; description: string; processing: boolean; close: () => void; submit: () => void; label: string; busyLabel: string }) { return <div className="seller-return-action-form"><strong>{title}</strong><p>{description}</p><FormButtons processing={processing} close={close} submit={submit} label={label} busyLabel={busyLabel} /></div>; }
