package com.giftmarket.admin.service;
import com.giftmarket.admin.exception.AdminCancellationException;import com.giftmarket.auth.exception.AuthenticationException;import com.giftmarket.order.entity.*;import com.giftmarket.order.repository.*;import com.giftmarket.payment.repository.*;import com.giftmarket.user.entity.*;import com.giftmarket.user.repository.UserRepository;import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;import org.springframework.data.domain.*;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.BDDMockito.given;import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class AdminCancellationServiceTest{
 @Mock UserRepository users;@Mock OrderCancellationRepository cancellations;@Mock OrderCancellationItemRepository items;@Mock PaymentRepository payments;@Mock PaymentCancellationRepository refunds;@Mock User admin;AdminCancellationService service;
 @BeforeEach void setUp(){service=new AdminCancellationService(users,cancellations,items,payments,refunds);}void admin(){given(users.findById(1L)).willReturn(Optional.of(admin));given(admin.getRole()).willReturn(UserRole.ADMIN);}
 @Test void rejectsNullAdmin(){assertThatThrownBy(()->service.getCancellations(null,0,20,null,null,null)).isInstanceOf(AuthenticationException.class).hasMessage("인증이 필요합니다.");verifyNoInteractions(cancellations);}
 @Test void rejectsMissingAdmin(){given(users.findById(1L)).willReturn(Optional.empty());assertThatThrownBy(()->service.getCancellation(1L,2L)).isInstanceOf(AuthenticationException.class).hasMessage("사용자를 찾을 수 없습니다.");}
 @Test void rejectsNonAdmin(){given(users.findById(1L)).willReturn(Optional.of(admin));given(admin.getRole()).willReturn(UserRole.USER);assertThatThrownBy(()->service.getCancellation(1L,2L)).isInstanceOf(AuthenticationException.class).hasMessage("관리자 권한이 필요합니다.");}
 @Test void passesTrimmedFiltersPaginationAndSort(){admin();given(cancellations.findAdminCancellations(any(),any(),any(),any())).willReturn(Page.empty());service.getCancellations(1L,2,20,"  GM  ",OrderCancellationStatus.REQUESTED,true);ArgumentCaptor<Pageable> p=ArgumentCaptor.forClass(Pageable.class);verify(cancellations).findAdminCancellations(eq("GM"),eq(OrderCancellationStatus.REQUESTED),eq(true),p.capture());assertThat(p.getValue().getPageNumber()).isEqualTo(2);assertThat(p.getValue().getSort().getOrderFor("requestedAt").isDescending()).isTrue();assertThat(p.getValue().getSort().getOrderFor("id").isDescending()).isTrue();}
 @Test void emptyPageDoesNotRunBatchQueries(){admin();given(cancellations.findAdminCancellations(any(),any(),any(),any())).willReturn(Page.empty());var r=service.getCancellations(1L,0,20," ",null,false);assertThat(r.content()).isEmpty();verifyNoInteractions(items,refunds);}
 @Test void throwsNotFound(){admin();given(cancellations.findAdminById(99L)).willReturn(Optional.empty());assertThatThrownBy(()->service.getCancellation(1L,99L)).isInstanceOf(AdminCancellationException.class).hasMessage("취소 요청을 찾을 수 없습니다.");}
}
