"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { getAdminExchange } from "@/lib/admin-api";
import type { AdminExchangeDetail, AdminExchangeShipment } from "@/types/admin";

const label: Record<string,string> = { REQUESTED:"요청", APPROVED:"승인", PAYMENT_PENDING:"배송비 결제 대기", COLLECTING:"회수 중", RECEIVED:"입고", INSPECTED:"검수 완료", RESHIPPING:"재출고", COMPLETED:"완료", REJECTED:"거절", CANCELED:"취소", FAILED:"실패", BUYER:"구매자", SELLER:"판매자", RESTOCKABLE:"재입고 가능", NON_RESTOCKABLE:"재입고 불가", READY:"결제 준비", SUCCEEDED:"결제 완료", EXPIRED:"만료", COMPENSATION_REQUIRED:"보상 처리 필요" };
const dateTime = (value: string | null) => value ? new Date(value).toLocaleString("ko-KR") : "-";
const won = (value: number) => `${value.toLocaleString("ko-KR")}원`;
function Shipment({ title, shipment }: { title:string; shipment:AdminExchangeShipment | null }) { return <section className="admin-user-detail-card"><header><p>SHIPMENT</p><h2>{title}</h2></header>{shipment ? <dl><div><dt>유형</dt><dd>{shipment.type}</dd></div><div><dt>상태</dt><dd>{shipment.status}</dd></div><div><dt>송장</dt><dd>{shipment.shippingCompany} {shipment.trackingNumber}</dd></div><div><dt>출고</dt><dd>{dateTime(shipment.shippedAt)}</dd></div><div><dt>배송 완료</dt><dd>{dateTime(shipment.deliveredAt)}</dd></div></dl> : <p className="admin-user-detail-empty">등록된 배송이 없습니다.</p>}</section>; }

export default function Page() {
  const exchangeId = Number(useParams<{ exchangeId:string }>().exchangeId);
  const [exchange,setExchange] = useState<AdminExchangeDetail | null>(null); const [loading,setLoading] = useState(true); const [error,setError] = useState("");
  const load = useCallback(async () => { if (!Number.isSafeInteger(exchangeId) || exchangeId < 1) { setError("올바르지 않은 교환 번호입니다."); setLoading(false); return; } try { setLoading(true); setError(""); setExchange(await getAdminExchange(exchangeId)); } catch (caught) { setError(caught instanceof Error ? caught.message : "교환 정보를 불러오지 못했습니다."); } finally { setLoading(false); } }, [exchangeId]);
  useEffect(() => { // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [load]);
  return <main className="admin-user-detail-page"><Link href="/admin/exchanges" className="admin-user-back-link">← 교환 목록으로 돌아가기</Link>
    {error && <div className="admin-dashboard-error"><span>{error}</span><button onClick={load}>다시 시도</button></div>}
    {loading && !exchange ? <div className="admin-user-state">교환 정보를 불러오고 있습니다.</div> : exchange ? <><header className="admin-user-detail-header"><div><p>EXCHANGE DETAIL · #{exchange.exchangeId}</p><h1>교환 상세</h1><span>{exchange.order.orderNumber} · {dateTime(exchange.requestedAt)}</span></div><span className={`admin-cancellation-badge is-${exchange.status.toLowerCase()}`}>{label[exchange.status]}</span></header>
      <div className="admin-user-detail-grid">
        <section className="admin-user-detail-card"><header><p>REQUEST</p><h2>교환 요청</h2></header><dl><div><dt>사유 유형</dt><dd>{exchange.reasonType}</dd></div><div><dt>사유</dt><dd>{exchange.reason}</dd></div><div><dt>귀책</dt><dd>{exchange.responsibility ? label[exchange.responsibility] : "미확정"}</dd></div><div><dt>거절 사유</dt><dd>{exchange.rejectedReason || "-"}</dd></div></dl></section>
        <section className="admin-user-detail-card"><header><p>ORDER / BUYER</p><h2>주문 / 구매자</h2></header><dl><div><dt>주문번호</dt><dd>{exchange.order.orderNumber}</dd></div><div><dt>구매자</dt><dd>{exchange.buyer.name} · {exchange.buyer.email || "-"}</dd></div></dl><Link href={`/admin/orders/${exchange.order.orderId}`} className="admin-seller-owner-button">주문 상세 →</Link><Link href={`/admin/users/${exchange.buyer.userId}`} className="admin-product-store-link">회원 상세 →</Link></section>
        <section className="admin-user-detail-card"><header><p>SELLER</p><h2>판매자 주문</h2></header><dl><div><dt>스토어</dt><dd>{exchange.seller.storeName}</dd></div><div><dt>상태</dt><dd>{exchange.seller.status}</dd></div></dl><Link href={`/admin/sellers/${exchange.seller.sellerId}`} className="admin-seller-owner-button">판매자 상세 →</Link></section>
        <section className="admin-user-detail-card"><header><p>SHIPPING PAYMENT</p><h2>교환 배송비 결제</h2></header>{exchange.shippingPayment ? <dl><div><dt>금액</dt><dd>{won(exchange.shippingPayment.amount)}</dd></div><div><dt>상태</dt><dd>{label[exchange.shippingPayment.status] || exchange.shippingPayment.status}</dd></div><div><dt>요청</dt><dd>{dateTime(exchange.shippingPayment.requestedAt)}</dd></div><div><dt>결제 완료</dt><dd>{dateTime(exchange.shippingPayment.succeededAt)}</dd></div><div><dt>실패</dt><dd>{dateTime(exchange.shippingPayment.failedAt)}</dd></div><div><dt>만료</dt><dd>{dateTime(exchange.shippingPayment.expiredAt)}</dd></div><div><dt>실패 코드</dt><dd>{exchange.shippingPayment.failureCode || "-"}</dd></div></dl> : <p className="admin-user-detail-empty">구매자 배송비 결제가 없습니다.</p>}</section>
        <Shipment title="회수 배송" shipment={exchange.collectionShipment} /><Shipment title="재출고 배송" shipment={exchange.outboundShipment} />
        <section className="admin-user-detail-card admin-order-groups"><header><p>ITEMS / VARIANTS</p><h2>교환 상품과 옵션 변경</h2></header><div className="admin-exchange-items">{exchange.items.map(item => <article key={item.exchangeItemId}><div className="admin-exchange-product"><Link href={`/admin/products/${item.productId}`}>{item.productName}</Link><span>교환 {item.exchangeQuantity}개 · 누적 완료 {item.exchangedQuantity}개</span></div><div className="admin-exchange-variant"><div><small>기존 옵션</small><strong>{item.originalOptionSnapshot || "옵션 없음"}</strong><span>{won(item.originalUnitPrice)} · {item.originalSku || "SKU 없음"}</span></div><b>→</b><div><small>교환 대상 옵션</small><strong>{item.targetOptionSnapshot || "옵션 없음"}</strong><span>{won(item.targetUnitPrice)} · {item.targetSku || "SKU 없음"}</span></div></div>{item.sameVariant && <p className="admin-exchange-same">동일 옵션 재교환</p>}<dl><div><dt>원 주문 수량</dt><dd>{item.originalQuantity}</dd></div><div><dt>검수 결과</dt><dd>{item.inspectionResult ? label[item.inspectionResult] : "미검수"}</dd></div><div><dt>재입고 수량</dt><dd>{item.restockedQuantity}</dd></div><div><dt>예약 / 소비 / 해제</dt><dd>{item.reservedQuantity} / {item.consumedQuantity} / {item.releasedQuantity}</dd></div></dl></article>)}</div></section>
        <section className="admin-user-detail-card admin-order-groups"><header><p>TIMELINE</p><h2>처리 타임라인</h2></header><ol className="admin-cancellation-timeline">{[["요청",exchange.requestedAt],["승인",exchange.approvedAt],["결제 대기",exchange.paymentPendingAt],["결제 기한",exchange.paymentDueAt],["회수",exchange.collectingAt],["입고",exchange.receivedAt],["검수",exchange.inspectedAt],["재출고",exchange.reshippingAt],["완료",exchange.completedAt],["거절",exchange.rejectedAt],["취소",exchange.canceledAt],["실패",exchange.failedAt]].filter((entry): entry is [string,string] => Boolean(entry[1])).map(([name,time]) => <li key={name}><strong>{name}</strong><span>{dateTime(time)}</span></li>)}</ol></section>
      </div></> : null}
  </main>;
}
